# Generated by Django 3.2.8 on 2024-01-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
